version: '3.8'
services:
  rpimon:
    image: oleksamarko/rpimon-debian-stable
    container_name: rpimon
    volumes:
      - /opt/vc:/opt/vc
      - /boot:/boot
      - /sys:/dockerhost/sys:ro
      - /etc:/dockerhost/etc:ro
      - /proc:/dockerhost/proc:ro
      - /usr/lib:/dockerhost/usr/lib:ro
    devices:
      - "/dev/vchiq:/dev/vchiq"
    restart: unless-stopped
    ports:
      - 8888:8888
